version: "3.8"

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
#    command: sh -c './wait-for db:5432 -- java -jar spring-app.jar'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - "8080:8080"
    restart: on-failure

  db:
    image: postgres:14-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
